name: zefyrka
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter based on Zefyr package.
version: 1.6.1
homepage: https://github.com/glynskyi/zefyrka

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  url_launcher: ^6.2.5
#  quill_format: # ^1.0.2
  notus_format: # ^1.0.3
    git:
      url: https://github.com/Yom3n/notus_format_fork
      ref: html

  characters: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
